# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(972, 245)
        self.buttonOK = QtWidgets.QPushButton(Dialog)
        self.buttonOK.setGeometry(QtCore.QRect(390, 180, 141, 41))
        self.buttonOK.setObjectName("buttonOK")
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setGeometry(QtCore.QRect(780, 40, 181, 121))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setHandleWidth(8)
        self.splitter.setObjectName("splitter")
        self.RDFDatatypes = QtWidgets.QPushButton(self.splitter)
        self.RDFDatatypes.setObjectName("RDFDatatypes")
        self.InstanceData = QtWidgets.QPushButton(self.splitter)
        self.InstanceData.setObjectName("InstanceData")
        self.SHACLConstraints = QtWidgets.QPushButton(self.splitter)
        self.SHACLConstraints.setObjectName("SHACLConstraints")
        self.splitter_2 = QtWidgets.QSplitter(Dialog)
        self.splitter_2.setGeometry(QtCore.QRect(20, 40, 751, 111))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setHandleWidth(10)
        self.splitter_2.setObjectName("splitter_2")
        self.labelSelectRDFmap = QtWidgets.QLabel(self.splitter_2)
        self.labelSelectRDFmap.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelSelectRDFmap.setText("")
        self.labelSelectRDFmap.setObjectName("labelSelectRDFmap")
        self.labelSelectData = QtWidgets.QLabel(self.splitter_2)
        self.labelSelectData.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelSelectData.setText("")
        self.labelSelectData.setObjectName("labelSelectData")
        self.labelSelectDataSHACL = QtWidgets.QLabel(self.splitter_2)
        self.labelSelectDataSHACL.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelSelectDataSHACL.setText("")
        self.labelSelectDataSHACL.setObjectName("labelSelectDataSHACL")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.buttonOK.setText(_translate("Dialog", "Validate"))
        self.RDFDatatypes.setText(_translate("Dialog", "Select Datatype mapping"))
        self.InstanceData.setText(_translate("Dialog", "Select data to validate"))
        self.SHACLConstraints.setText(_translate("Dialog", "Select SHACL Constraints"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
